// Generated by `zfa package create-plugin` — value codec contract.
import 'package:test/test.dart';
import 'package:html_to_markdown_ffi/html_to_markdown_ffi.dart';

void main() {
  test('i32 encodes to an int', () {
    expect(HtmlToMarkdownFfiI32(42).encode(), 42);
  });

  test('i64 encodes to a decimal string and decodes back', () {
    final value = HtmlToMarkdownFfiI64(BigInt.parse('9007199254740993'));

    expect(value.encode(), '9007199254740993');
    expect(
      (HtmlToMarkdownFfiValue.decode(value.encode()) as HtmlToMarkdownFfiI64).value,
      BigInt.parse('9007199254740993'),
    );
  });

  test('f64 encodes to a double', () {
    expect(HtmlToMarkdownFfiF64(0.5).encode(), 0.5);
  });
}
