// GENERATED - DO NOT EDIT
// Generated by zfa for: HtmConversion
// zfa make HtmConversion --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/htm_conversion/htm_conversion.dart';
import '../../domain/repositories/htm_conversion_repository.dart';
import '../datasources/htm_conversion/htm_conversion_datasource.dart';

class DataHtmConversionRepository
    with Loggable, FailureHandler
    implements HtmConversionRepository {
  DataHtmConversionRepository(this._dataSource);

  final HtmConversionDataSource _dataSource;

  @override
  Future<HtmConversion> get(QueryParams<HtmConversion> params) {
    return _dataSource.get(params);
  }

  @override
  Future<HtmConversion> update(
    UpdateParams<String, HtmConversionPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<HtmConversion> toggle(
    ToggleParams<String, Field<HtmConversion, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
