// GENERATED - DO NOT EDIT
// Generated by zfa for: HtmConversion
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/htm_conversion/htm_conversion.dart';
import '../../repositories/htm_conversion_repository.dart';

class GetHtmConversionUseCase
    extends UseCase<HtmConversion, QueryParams<HtmConversion>> {
  GetHtmConversionUseCase(this._repository);

  final HtmConversionRepository _repository;

  @override
  Future<HtmConversion> execute(
    QueryParams<HtmConversion> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
