// GENERATED - DO NOT EDIT
// Generated by zfa for: HtmConversion
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/htm_conversion/htm_conversion.dart';
import '../../repositories/htm_conversion_repository.dart';

class UpdateHtmConversionUseCase
    extends UseCase<HtmConversion, UpdateParams<String, HtmConversionPatch>> {
  UpdateHtmConversionUseCase(this._repository);

  final HtmConversionRepository _repository;

  @override
  Future<HtmConversion> execute(
    UpdateParams<String, HtmConversionPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
