// GENERATED by zfa datasource — DO NOT EDIT BY HAND.
// Regenerate with: zfa datasource create HtmConversion (--force to overwrite). Variant: datasource interface.

// GENERATED - DO NOT EDIT
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/htm_conversion/htm_conversion.dart';

abstract class HtmConversionDataSource with Loggable, FailureHandler {
  Future<HtmConversion> get(QueryParams<HtmConversion> params);
  Future<HtmConversion> update(UpdateParams<String, HtmConversionPatch> params);
  Future<HtmConversion> toggle(
    ToggleParams<String, Field<HtmConversion, dynamic>> params,
  );
}

// END GENERATED
