// GENERATED by zfa datasource — DO NOT EDIT BY HAND.
// Regenerate with: zfa datasource create HtmConversion (--force to overwrite). Variant: remote datasource.

// GENERATED - DO NOT EDIT
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/htm_conversion/htm_conversion.dart';
import 'htm_conversion_datasource.dart';

class HtmConversionRemoteDataSource
    with Loggable, FailureHandler
    implements HtmConversionDataSource {
  @override
  Future<HtmConversion> get(QueryParams<HtmConversion> params) async {
    throw UnimplementedError('Implement remote get');
  }

  @override
  Future<HtmConversion> update(
    UpdateParams<String, HtmConversionPatch> params,
  ) async {
    throw UnimplementedError('Implement remote update');
  }

  @override
  Future<HtmConversion> toggle(
    ToggleParams<String, Field<HtmConversion, dynamic>> params,
  ) async {
    throw UnimplementedError('Implement remote toggle');
  }
}

// END GENERATED
