// Native datasource for HtmConversion — the zuraffa data layer's wrapper
// around the EXISTING dart:ffi bridge (spec 064 FR-004). The binding logic
// (options json -> handle -> htm_convert -> result json) is preserved
// verbatim from the pre-migration `convert()`; only its home moved here.
// NOT generated by zfa — an implementation of the generated
// [HtmConversionDataSource] contract.
import 'dart:ffi';

import 'package:ffi/ffi.dart';
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/htm_conversion/htm_conversion.dart';
import '../../../../exceptions.dart';
import '../../../../native_library.dart';
import '../../../../visitor.dart';
import '../../../../visitor_bridge.dart';
import 'htm_conversion_datasource.dart';

/// Converts HTML to Markdown through the native bridge.
///
/// The request travels as an [HtmConversion] entity (`html` + `optionsJson`);
/// the bridge's result json lands back in `resultJson`. [convertNow] is the
/// synchronous in-process path (dart:ffi is synchronous); [get] adapts it to
/// the generated async contract.
class NativeHtmConversionDataSource
    with Loggable, FailureHandler
    implements HtmConversionDataSource {
  NativeHtmConversionDataSource({NativeLibrary? library})
      : _libraryOverride = library;

  final NativeLibrary? _libraryOverride;

  NativeLibrary get _library => _libraryOverride ?? NativeLibrary();

  /// The preserved synchronous bridge call. [visitor] travels out of band
  /// (it is a callback, not JSON). Throws the preserved public exceptions
  /// ([InvalidInputException], [ConversionErrorException]) via
  /// [checkLastError].
  HtmConversion convertNow(HtmConversion request, {Visitor? visitor}) {
    final lib = _library;
    final arena = Arena();
    VisitorBridge? bridge;
    try {
      final htmlPtr = request.html.toNativeUtf8(allocator: arena);
      final optionsJson = request.optionsJson;
      final optionsPtr = _createOptions(lib, optionsJson, arena);

      bridge = visitor == null ? null : VisitorBridge(visitor);
      if (bridge != null) {
        bridge.attach(optionsPtr);
      }

      final resultPtr = lib.htmConvert(htmlPtr, optionsPtr);
      if (resultPtr == nullptr) {
        checkLastError();
        throw const ConversionErrorException(
            'Conversion returned null result');
      }

      final jsonPtr = lib.htmConversionResultToJson(resultPtr);
      final json = jsonPtr.toDartString();
      lib.htmFreeString(jsonPtr);

      lib.htmConversionResultFree(resultPtr);
      return request.copyWith(resultJson: json);
    } finally {
      bridge?.close();
      arena.releaseAll();
    }
  }

  dynamic _createOptions(
    NativeLibrary lib,
    String optionsJson,
    Arena arena,
  ) {
    final jsonPtr = optionsJson.toNativeUtf8(allocator: arena);
    final handle = lib.htmConversionOptionsFromJson(jsonPtr);
    if (handle == nullptr) {
      checkLastError();
      throw const ConversionErrorException(
          'Failed to create conversion options');
    }
    return handle;
  }

  @override
  Future<HtmConversion> get(QueryParams<HtmConversion> params) async {
    final request = params.params?['request'];
    if (request is! HtmConversion) {
      throw ArgumentError.value(
        request,
        'params[request]',
        'Expected the HtmConversion request entity',
      );
    }
    final visitor = params.params?['visitor'];
    return convertNow(request, visitor: visitor is Visitor ? visitor : null);
  }

  @override
  Future<HtmConversion> update(
    UpdateParams<String, HtmConversionPatch> params,
  ) async {
    throw UnsupportedError(
        'HtmConversion is produced by conversion, not updated in place');
  }

  @override
  Future<HtmConversion> toggle(
    ToggleParams<String, Field<HtmConversion, dynamic>> params,
  ) async {
    throw UnsupportedError(
        'HtmConversion is produced by conversion, not toggled in place');
  }
}
