// GENERATED - DO NOT EDIT
// Generated by zfa for: HtmConversion
// zfa make HtmConversion --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/htm_conversion/htm_conversion.dart';

abstract class HtmConversionRepository {
  Future<HtmConversion> get(QueryParams<HtmConversion> params);
  Future<HtmConversion> update(UpdateParams<String, HtmConversionPatch> params);
  Future<HtmConversion> toggle(
    ToggleParams<String, Field<HtmConversion, dynamic>> params,
  );
}

// END GENERATED
