// Auto-generated by Zorphy (`zfa entity create -n HtmConversion`); fields
// filled per spec 064 data-model.md — the internal conversion envelope the
// generated repository/datasource/usecase stack operates on. The preserved
// public API types map to/from this envelope at the service boundary.
import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'htm_conversion.zorphy.dart';
part 'htm_conversion.g.dart';

/// HtmConversion entity — one conversion request/result pair, identified
/// by [id] (assigned per call by the service, mirroring the family's
/// module-registry pattern).
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HtmConversion {
  String get html;
  String get optionsJson;
  String get resultJson;
  String get id;

}
